import { useMemo, useState } from 'react'
import { Activity, Bot, CloudRain, Mountain, Route, ShieldAlert, Sparkles, Waves } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Button } from '../lib/shadcn/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../lib/shadcn/select'
import { Slider } from '../lib/shadcn/slider'

type RiskLevel = 'LOW' | 'MODERATE' | 'HIGH' | 'EXTREME'
type Location = { name: string; state: string; risk: number; rainfall: number; moisture: number; slope: number; exposure: number; roads: number; hospitals: number; schools: number; settlements: number; x: string; y: string }

const locations: Location[] = [
  { name: 'Guwahati', state: 'Assam', risk: 47, rainfall: 78, moisture: 52, slope: 24, exposure: 2440, roads: 9, hospitals: 4, schools: 10, settlements: 8, x: '30%', y: '62%' },
  { name: 'Shillong', state: 'Meghalaya', risk: 78, rainfall: 142, moisture: 68, slope: 32, exposure: 4820, roads: 17, hospitals: 2, schools: 6, settlements: 12, x: '36%', y: '66%' },
  { name: 'Gangtok', state: 'Sikkim', risk: 91, rainfall: 210, moisture: 86, slope: 38, exposure: 5390, roads: 22, hospitals: 2, schools: 5, settlements: 15, x: '18%', y: '29%' },
  { name: 'Imphal', state: 'Manipur', risk: 62, rainfall: 104, moisture: 59, slope: 28, exposure: 3370, roads: 13, hospitals: 3, schools: 8, settlements: 10, x: '56%', y: '78%' },
  { name: 'Aizawl', state: 'Mizoram', risk: 83, rainfall: 168, moisture: 74, slope: 35, exposure: 6080, roads: 20, hospitals: 2, schools: 7, settlements: 16, x: '61%', y: '89%' },
  { name: 'Kohima', state: 'Nagaland', risk: 53, rainfall: 85, moisture: 54, slope: 26, exposure: 2180, roads: 11, hospitals: 2, schools: 4, settlements: 7, x: '71%', y: '59%' },
  { name: 'Itanagar', state: 'Arunachal Pradesh', risk: 35, rainfall: 52, moisture: 43, slope: 20, exposure: 1460, roads: 7, hospitals: 1, schools: 3, settlements: 5, x: '78%', y: '35%' },
  { name: 'Agartala', state: 'Tripura', risk: 18, rainfall: 28, moisture: 31, slope: 12, exposure: 580, roads: 3, hospitals: 2, schools: 2, settlements: 3, x: '22%', y: '87%' },
]
const trend = [{ day: 'Mon', rainfall: 48, soil: 42, risk: 29 }, { day: 'Tue', rainfall: 62, soil: 48, risk: 38 }, { day: 'Wed', rainfall: 74, soil: 54, risk: 49 }, { day: 'Thu', rainfall: 96, soil: 59, risk: 61 }, { day: 'Fri', rainfall: 123, soil: 64, risk: 69 }, { day: 'Sat', rainfall: 142, soil: 68, risk: 78 }, { day: 'Today', rainfall: 136, soil: 67, risk: 76 }]
const seasonal = [{ month: 'Jan', events: 2 }, { month: 'Mar', events: 5 }, { month: 'May', events: 19 }, { month: 'Jun', events: 38 }, { month: 'Jul', events: 52 }, { month: 'Aug', events: 47 }, { month: 'Sep', events: 31 }, { month: 'Nov', events: 4 }]

function riskLevel(value: number): RiskLevel { return value >= 86 ? 'EXTREME' : value >= 65 ? 'HIGH' : value >= 40 ? 'MODERATE' : 'LOW' }
function riskStyle(level: RiskLevel) { return { LOW: { text: 'text-emerald-400', bg: 'bg-emerald-400', surface: 'border-emerald-400/25 bg-emerald-400/10' }, MODERATE: { text: 'text-yellow-300', bg: 'bg-yellow-300', surface: 'border-yellow-300/25 bg-yellow-300/10' }, HIGH: { text: 'text-orange-400', bg: 'bg-orange-400', surface: 'border-orange-400/25 bg-orange-400/10' }, EXTREME: { text: 'text-red-400', bg: 'bg-red-400', surface: 'border-red-400/25 bg-red-400/10' } }[level] }
function Detail({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border bg-secondary/45 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div> }

export default function AdvancedTools() {
  const [locationName, setLocationName] = useState('Shillong')
  const [filter, setFilter] = useState<'ALL' | RiskLevel>('ALL')
  const [layer, setLayer] = useState('Risk Level')
  const [routeStart, setRouteStart] = useState('Shillong')
  const [routeEnd, setRouteEnd] = useState('Aizawl')
  const [chosenRoute, setChosenRoute] = useState('Balanced')
  const [rainfall, setRainfall] = useState(142)
  const [moisture, setMoisture] = useState(68)
  const [slope, setSlope] = useState(32)
  const [elevation, setElevation] = useState(1245)
  const [cover, setCover] = useState('Forest')
  const [question, setQuestion] = useState('Why is this location high risk?')
  const [details, setDetails] = useState(false)
  const location = useMemo(() => locations.find((item) => item.name === locationName) ?? locations[1]!, [locationName])
  const currentLevel = riskLevel(location.risk)
  const currentStyle = riskStyle(currentLevel)
  const alerts = locations.filter((item) => item.risk >= 40 && (filter === 'ALL' || riskLevel(item.risk) === filter))
  const simulationRisk = Math.min(98, Math.max(6, Math.round(rainfall * .19 + moisture * .28 + slope * .62 + (cover === 'Barren' ? 11 : cover === 'Urban' ? 7 : 0) - 20)))
  const simulationLevel = riskLevel(simulationRisk)
  const routes = [{ name: 'Shortest', distance: 52, exposure: 82, zones: 4 }, { name: 'Balanced', distance: 58, exposure: 48, zones: 2 }, { name: 'Safest', distance: 63, exposure: 18, zones: 1 }]
  const answer = question.includes('route') ? `For the ${routeStart} to ${routeEnd} journey, the ${chosenRoute.toLowerCase()} option is recommended in this prototype because it crosses fewer estimated high-risk areas.` : question.includes('do') ? 'Treat this as a decision-support indicator. Review authorized local advisories, avoid exposed roads during heavy rain, and do not enter restricted areas.' : `For ${location.name}, the prototype estimate is driven by ${location.rainfall} mm rainfall, ${location.moisture}% soil moisture, and a ${location.slope}° slope. This is not a guaranteed prediction.`
  const mapRisk = [0, 50, 100, 150, 200, 250, 300].map((value) => ({ rainfall: value, risk: Math.min(98, Math.max(4, Math.round(value * .19 + moisture * .28 + slope * .62 - 20))) }))

  const simulatorControls: { label: string; value: number; max: number; setter: (value: number) => void; unit: string }[] = [{ label: 'Rainfall', value: rainfall, max: 300, setter: setRainfall, unit: 'mm' }, { label: 'Soil moisture', value: moisture, max: 100, setter: setMoisture, unit: '%' }, { label: 'Slope', value: slope, max: 60, setter: setSlope, unit: '°' }, { label: 'Elevation', value: elevation, max: 3000, setter: setElevation, unit: 'm' }]
  return <main className="min-h-screen bg-background px-4 pb-16 pt-8 text-foreground sm:px-6"><div className="mx-auto max-w-7xl">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Decision-support upgrades</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Early warning & field intelligence</h1><p className="mt-2 text-sm text-muted-foreground">Prototype Demonstration Data · all outputs are simulated estimates.</p></div><Button variant="outline" className="rounded-xl text-xs" onClick={() => { setRainfall(142); setMoisture(68); setSlope(32); setElevation(1245); setCover('Forest') }}>Reset simulator</Button></div>

    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Why did the risk change?</p><h2 className="mt-1 text-xl font-semibold">{location.name}, {location.state}</h2></div><Select value={locationName} onValueChange={setLocationName}><SelectTrigger className="w-44 bg-secondary text-xs"><SelectValue /></SelectTrigger><SelectContent>{locations.map((item) => <SelectItem key={item.name} value={item.name}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="mt-6 grid grid-cols-3 gap-3"><Detail label="Previous risk" value={`${Math.max(8, location.risk - 26)}%`} /><Detail label="Current risk" value={`${location.risk}%`} /><div className={`rounded-xl border p-3 ${currentStyle.surface}`}><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Change</p><p className={`mt-1 text-lg font-semibold ${currentStyle.text}`}>+26%</p></div></div><div className="mt-5 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><p><CloudRain className="mr-2 inline h-4 w-4 text-primary" />Rainfall increased by 43%</p><p><Waves className="mr-2 inline h-4 w-4 text-primary" />Soil moisture increased by 18%</p><p><Mountain className="mr-2 inline h-4 w-4 text-primary" />High slope exposure</p><p><Activity className="mr-2 inline h-4 w-4 text-primary" />Terrain instability increased</p></div><Button variant="outline" onClick={() => setDetails(!details)} className="mt-5 rounded-xl text-xs">Why is the risk high? <Sparkles className="ml-2 h-3.5 w-3.5" /></Button>{details ? <div className="mt-4 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm leading-6 text-muted-foreground">Wetter ground plus heavy rainfall over sloped terrain is raising this AI/model-based risk estimate. In a real deployment, this needs validated local datasets and expert interpretation. It is not a certainty.</div> : null}</div><div className={`rounded-3xl border p-6 shadow-retool-sm ${currentStyle.surface}`}><div className="flex items-center gap-3"><ShieldAlert className={`h-7 w-7 ${currentStyle.text}`} /><div><p className={`text-[10px] font-bold uppercase tracking-wider ${currentStyle.text}`}>Early warning indicator</p><h2 className="text-xl font-semibold">{currentLevel} · {location.risk}%</h2></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Avoid exposed roads during sustained rain, check authorized advisories, and consider a lower-risk route.</p><p className="mt-5 rounded-xl border border-border bg-background/40 p-3 text-xs text-muted-foreground">Real deployment requires validated data, testing, domain expertise and authorized emergency-management integration.</p></div></section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Early Warning Center</p><h2 className="mt-1 text-xl font-semibold">Active regional alerts</h2></div><div className="flex rounded-xl bg-secondary p-1">{(['ALL', 'EXTREME', 'HIGH', 'MODERATE'] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-2 py-1.5 text-[10px] font-bold ${filter === item ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>{item === 'ALL' ? 'All' : item}</button>)}</div></div><div className="mt-5 space-y-2">{alerts.map((item) => { const itemLevel = riskLevel(item.risk); const itemStyle = riskStyle(itemLevel); return <button key={item.name} onClick={() => setLocationName(item.name)} className={`w-full rounded-2xl border p-3 text-left transition hover:-translate-y-0.5 ${itemStyle.surface}`}><div className="flex justify-between"><div><p className={`text-[10px] font-bold uppercase ${itemStyle.text}`}>{itemLevel}</p><p className="mt-1 text-sm font-semibold">{item.state} — {item.name} zone</p><p className="mt-1 text-xs text-muted-foreground">{item.exposure.toLocaleString()} people · {item.roads} km exposed roads</p></div><p className={`text-lg font-semibold ${itemStyle.text}`}>{item.risk}%</p></div></button> })}</div></div>
      <div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Multi-layer risk map</p><h2 className="mt-1 text-xl font-semibold">NER geospatial layers</h2></div><Select value={layer} onValueChange={setLayer}><SelectTrigger className="w-48 bg-secondary text-xs"><SelectValue /></SelectTrigger><SelectContent>{['Risk Level', 'Rainfall', 'Slope', 'Soil Moisture', 'Population Exposure', 'Roads'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="relative mt-5 h-[370px] overflow-hidden rounded-2xl border border-border bg-[#0b1d2e] [background-image:radial-gradient(circle_at_38%_34%,rgba(42,148,126,.18),transparent_23%),linear-gradient(25deg,transparent_42%,rgba(87,119,122,.28)_42.5%,transparent_44%,transparent_56%,rgba(87,119,122,.16)_56.5%,transparent_58%)]"><p className="absolute left-4 top-4 z-10 rounded-lg bg-card/80 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{layer} · simulated layer</p>{locations.map((item) => { const itemStyle = riskStyle(riskLevel(item.risk)); return <button key={item.name} onClick={() => setLocationName(item.name)} style={{ left: item.x, top: item.y }} className="absolute z-10 group"><span className={`block h-4 w-4 rounded-full border-2 border-background ${itemStyle.bg} ${item.name === location.name ? 'scale-150 shadow-[0_0_0_7px_rgba(45,212,191,.16)]' : ''} transition`} /><span className="pointer-events-none absolute left-5 top-0 hidden w-max rounded-lg border border-border bg-card px-2 py-1 text-[10px] shadow-md group-hover:block">{item.name} · {item.risk}%</span></button> })}<div className="absolute bottom-4 left-4 rounded-xl border border-border bg-card/95 p-3 text-xs shadow-md"><p className="font-semibold">{location.name}, {location.state}</p><p className={`mt-1 text-[10px] font-bold uppercase ${currentStyle.text}`}>{currentLevel} · {location.risk}% probability</p><p className="mt-2 text-[10px] text-muted-foreground">{location.rainfall} mm · {location.moisture}% soil · {location.slope}° slope</p></div><div className="absolute bottom-4 right-4 rounded-xl border border-border bg-card/95 p-3 text-[10px] leading-5 text-muted-foreground shadow-md"><p>{location.exposure.toLocaleString()} potentially exposed</p><p>{location.roads} km nearby roads</p></div></div></div></section>

    <section className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Potential Exposure</p><h2 className="mt-1 text-xl font-semibold">Who and what could be affected?</h2><p className="mt-2 text-xs text-muted-foreground">Selected region: {location.name} · simulated exposure data</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Detail label="Population at risk" value={location.exposure.toLocaleString()} /><Detail label="Road network" value={`${location.roads} km`} /><Detail label="Hospitals" value={location.hospitals} /><Detail label="Schools" value={location.schools} /><Detail label="Settlements" value={location.settlements} /></div></div><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">What changed?</p><h2 className="mt-1 text-xl font-semibold">Last 24 hours</h2><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4">{[['08:00', 'Rainfall increased'], ['12:00', 'Soil moisture increased'], ['16:00', 'Risk moved upward'], ['18:00', 'Alert generated']].map(([time, label]) => <div key={time} className="border-l border-primary/50 pl-3"><p className="font-bold text-primary">{time}</p><p className="mt-1 text-muted-foreground">{label}</p></div>)}</div></div></section>

    <section id="routes" className="mt-5 rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Route intelligence</p><h2 className="mt-1 text-xl font-semibold">Safer route comparison</h2><div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Select value={routeStart} onValueChange={setRouteStart}><SelectTrigger className="bg-secondary text-sm"><SelectValue /></SelectTrigger><SelectContent>{locations.map((item) => <SelectItem key={`start-${item.name}`} value={item.name}>{item.name}, {item.state}</SelectItem>)}</SelectContent></Select><Select value={routeEnd} onValueChange={setRouteEnd}><SelectTrigger className="bg-secondary text-sm"><SelectValue /></SelectTrigger><SelectContent>{locations.filter((item) => item.name !== routeStart).map((item) => <SelectItem key={`end-${item.name}`} value={item.name}>{item.name}, {item.state}</SelectItem>)}</SelectContent></Select><Button className="rounded-xl text-xs">Recalculate <Route className="ml-2 h-3.5 w-3.5" /></Button></div><div className="mt-5 grid gap-3 md:grid-cols-3">{routes.map((item) => { const itemLevel = riskLevel(item.exposure); const itemStyle = riskStyle(itemLevel); const selected = chosenRoute === item.name; return <button key={item.name} onClick={() => setChosenRoute(item.name)} className={`rounded-2xl border p-5 text-left transition ${selected ? 'border-primary bg-primary/10 shadow-retool-sm' : 'border-border bg-secondary/25 hover:border-primary/40'}`}><div className="flex justify-between"><Route className={`h-5 w-5 ${selected ? 'text-primary' : itemStyle.text}`} /><span className={`text-[10px] font-bold uppercase ${itemStyle.text}`}>{itemLevel}</span></div><p className="mt-5 text-lg font-semibold">Route {item.name}</p><p className="mt-1 text-sm text-muted-foreground">{item.distance} km · {item.zones} high-risk zones crossed</p><div className="mt-4 h-1.5 rounded-full bg-secondary"><div className={`h-full rounded-full ${itemStyle.bg}`} style={{ width: `${item.exposure}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">Risk exposure: {item.exposure}% estimate</p></button> })}</div><p className="mt-4 text-xs text-muted-foreground">Route-risk values are prototype/demo estimates, not guaranteed safe routes.</p></section>

    <section id="simulator" className="mt-5 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Risk Simulator</p><h2 className="mt-1 text-xl font-semibold">Test changing environmental conditions</h2><p className="mt-2 text-xs text-muted-foreground">Simulation using prototype model/demo logic.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{simulatorControls.map((control) => <div key={control.label}><div className="mb-3 flex justify-between text-xs"><span className="font-medium">{control.label}</span><span className="text-primary">{control.value}{control.unit}</span></div><Slider value={[control.value]} max={control.max} step={1} onValueChange={(next) => { const first = next[0]; if (first !== undefined) control.setter(first) }} /></div>)}<div><p className="mb-3 text-xs font-medium">Land cover</p><Select value={cover} onValueChange={setCover}><SelectTrigger className="bg-secondary text-xs"><SelectValue /></SelectTrigger><SelectContent>{['Forest', 'Agriculture', 'Urban', 'Barren', 'Mixed'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div><div className={`mt-7 flex items-center gap-5 rounded-2xl border p-5 ${riskStyle(simulationLevel).surface}`}><Activity className={`h-9 w-9 ${riskStyle(simulationLevel).text}`} /><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Estimated landslide risk</p><p className={`text-3xl font-semibold ${riskStyle(simulationLevel).text}`}>{simulationRisk}% · {simulationLevel}</p></div></div></div><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Sensitivity curve</p><h2 className="mt-1 text-xl font-semibold">Risk vs rainfall</h2><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={mapRisk}><defs><linearGradient id="riskFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={.35} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" /><XAxis dataKey="rainfall" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><Tooltip contentStyle={{ background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 10, fontSize: 12 }} /><Area dataKey="risk" stroke="hsl(var(--primary))" strokeWidth={3} fill="url(#riskFill)" /></AreaChart></ResponsiveContainer></div></div></section>

    <section className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Historical Risk Trends</p><h2 className="mt-1 text-xl font-semibold">7-day environmental trend</h2><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" /><XAxis dataKey="day" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><Tooltip contentStyle={{ background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 10, fontSize: 12 }} /><Line dataKey="rainfall" stroke="hsl(var(--chart-2))" strokeWidth={2} /><Line dataKey="soil" stroke="hsl(var(--primary))" strokeWidth={2} /><Line dataKey="risk" stroke="hsl(var(--chart-4))" strokeWidth={2} /></LineChart></ResponsiveContainer></div></div><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">Historical landslide pattern</p><h2 className="mt-1 text-xl font-semibold">Seasonal demo pattern</h2><p className="mt-2 text-xs text-muted-foreground">Highest-risk season: June — September</p><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={seasonal}><XAxis dataKey="month" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><YAxis hide /><Tooltip contentStyle={{ background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 10, fontSize: 12 }} /><Bar dataKey="events" fill="hsl(var(--primary))" radius={6} /></BarChart></ResponsiveContainer></div></div></section>

    <section className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">LandslideGuard Assistant</p><h2 className="mt-1 flex items-center gap-2 text-xl font-semibold"><Bot className="h-5 w-5 text-primary" />Ask about this situation</h2><Select value={question} onValueChange={setQuestion}><SelectTrigger className="mt-5 bg-secondary text-xs"><SelectValue /></SelectTrigger><SelectContent>{['Why is this location high risk?', 'What factors are increasing the risk?', 'Which route is safer?', 'What should I do during a high-risk alert?'].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><div className="mt-4 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm leading-6 text-muted-foreground"><Bot className="mr-2 inline h-4 w-4 text-primary" />{answer}</div></div><div className="rounded-3xl border border-border bg-card p-6 shadow-retool-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">How our AI works</p><h2 className="mt-1 text-xl font-semibold">Detect → Predict → Explain → Protect</h2><div className="mt-5 grid gap-2 sm:grid-cols-4">{['Environmental Data', 'Data Preprocessing', 'Feature Engineering', 'Random Forest Model', 'Risk Probability', 'Explainable Factors', 'Warning + Map', 'Safer Route'].map((item, index) => <div key={item} className="rounded-xl border border-border bg-secondary/35 p-3 text-xs font-medium"><span className="mb-2 block text-[10px] text-primary">0{index + 1}</span>{item}</div>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">Inputs: rainfall, soil moisture, slope, elevation, land cover and historical landslide data. Model evaluation pending real-world dataset integration.</p></div></section>
  </div></main>
}
